<label>المدينة</label>
<select id="heard" name="city" class="form-control" onchange="s_city()">
      <option disabled selected>اختر المدينة</option>
      <?php 
      $get_cities = $engine->get_query("SELECT * FROM `cities`");
      while($show_cities = $get_cities->fetch_array()){?>
      <option value="<?=$show_cities['name']?>"><?=$show_cities['name']?></option>
      <?}?>
      <!-- <option value="الرياض">الرياض</option>
      <option value="الخرج">الخرج</option>
      <option value="المجمعة">المجمعة</option>
      <option value="المزاحمية">المزاحمية</option>
      <option value="الدرعية">الدرعية</option>
      <option value="الدوادمي">الدوادمي</option>
      <option value="القويعية">القويعية</option>
      <option value="الأفلاج">الأفلاج</option>
      <option value="وادي الدواسر ">وادي الدواسر </option>
      <option value="الزلفي">الزلفي</option>
      <option value="شقراء">شقراء</option>
      <option value="حوطة بني تميم ">حوطة بني تميم </option>
      <option value="عفيف">عفيف</option>
      <option value="الغاط">الغاط</option>
      <option value="السليل">السليل</option>
      <option value="ضرما">ضرما</option>
      <option value="رماح">رماح</option>
      <option value="ثادق">ثادق</option>
      <option value="حريملاء">حريملاء</option>
      <option value="الحريق">الحريق</option>
      <option value="مرات">مرات</option>
      <option value="الرين">الرين</option>
      <option value="مكة المكرمة ">مكة المكرمة </option>
      <option value="جدة">جدة</option>
      <option value="الطائف">الطائف</option>
      <option value="القنفذة">القنفذة</option>
      <option value="الليث">الليث</option>
      <option value="رابغ">رابغ</option>
      <option value="خليص">خليص</option>
      <option value="الخرمة">الخرمة</option>
      <option value="رنية">رنية</option>
      <option value="تربة">تربة</option>
      <option value="الجموم">الجموم</option>
      <option value="الكامل">الكامل</option>
      <option value="المويه">المويه</option>
      <option value="ميسان">ميسان</option>
      <option value="أضم">أضم</option>
      <option value="العرضيات">العرضيات</option>
      <option value="بحرة">بحرة</option>
      <option value="المدينة المنورة ">المدينة المنورة </option>
      <option value="ينبع">ينبع</option>
      <option value="العلا">العلا</option>
      <option value="الذهب">الذهب</option>
      <option value="الحناكية">الحناكية</option>
      <option value="بدر">بدر</option>
      <option value="خيبر">خيبر</option>
      <option value="العيص">العيص</option>
      <option value="وادي الفرع ">وادي الفرع </option>
      <option value="بريدة ">بريدة </option>
      <option value="عنيزة">عنيزة</option>
      <option value="الرس">الرس</option>
      <option value="الدمام">الدمام</option>
      <option value="المذنب">المذنب</option>
      <option value="البكيرية">البكيرية</option>
      <option value="البدائع">البدائع</option>
      <option value="الأسياح">الأسياح</option>
      <option value="النبهانية">النبهانية</option>
      <option value="الشماسية">الشماسية</option>
      <option value="عيون الجواء ">عيون الجواء </option>
      <option value="رياض الخبراء ">رياض الخبراء </option>
      <option value="عقلة الصقور ">عقلة الصقور </option>
      <option value="ضرية">ضرية</option>
      <option value="حفر الباطن ">حفر الباطن </option>
      <option value="الجبيل">الجبيل</option>
      <option value="القطيف">القطيف</option>
      <option value="الخبر">الخبر</option>
      <option value="الخفجي">الخفجي</option>
      <option value="رأس تنورة ">رأس تنورة </option>
      <option value="بقيق">بقيق</option>
      <option value="النعيرية">النعيرية</option>
      <option value="قرية العليا ">قرية العليا </option>
      <option value="العديد">العديد</option>
      <option value="رفحاء">رفحاء</option>
      <option value="حائل">حائل</option>
      <option value="ضبا">ضبا</option>
      <option value="طريب">طريب</option>
      <option value="البرك">البرك</option>
      <option value="الحائط">الحائط</option>
      <option value="منطقة أخرى">منطقة أخرى</option> -->
</select>
